version: '3.8'

services:
  protoc:
    build:
      context: .
      dockerfile: Dockerfile.protoc
    volumes:
      - .:/app
    command: ["sh", "-c", "protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/todo.proto"]

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"
    volumes:
      - .:/app
    command: ["go", "run", "server/main.go"]

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - .:/app
    depends_on:
      - server
    command: ["go", "run", "client/main.go"]